package com.rainlsilica.datagen;

import com.rainlsilica.item.PokemonGen1Photos;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.minecraft.registry.RegistryWrapper;

import java.util.concurrent.CompletableFuture;

public class ModENUSLangProvider extends FabricLanguageProvider {
    public ModENUSLangProvider(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput, registryLookup);
    }

    @Override
    public void generateTranslations(RegistryWrapper.WrapperLookup wrapperLookup, TranslationBuilder translationBuilder) {
        translationBuilder.add("itemGroup.pokemon_photo", "Pokemon Photo");

        // gen 1 normal
        translationBuilder.add(PokemonGen1Photos.BULBASAUR, "Bulbasaur");
        translationBuilder.add(PokemonGen1Photos.IVYSAUR, "Ivysaur");
        translationBuilder.add(PokemonGen1Photos.VENUSAUR, "Venusaur");
        translationBuilder.add(PokemonGen1Photos.CHARMANDER, "Charmander");
        translationBuilder.add(PokemonGen1Photos.CHARMELEON, "Charmeleon");
        translationBuilder.add(PokemonGen1Photos.CHARIZARD, "Charizard");
        translationBuilder.add(PokemonGen1Photos.SQUIRTLE, "Squirtle");
        translationBuilder.add(PokemonGen1Photos.WARTORTLE, "Wartortle");
        translationBuilder.add(PokemonGen1Photos.BLASTOISE, "Blastoise");
        translationBuilder.add(PokemonGen1Photos.CATERPIE, "Caterpie");
        translationBuilder.add(PokemonGen1Photos.METAPOD, "Metapod");
        translationBuilder.add(PokemonGen1Photos.BUTTERFREE, "Butterfree");
        translationBuilder.add(PokemonGen1Photos.WEEDLE, "Weedle");
        translationBuilder.add(PokemonGen1Photos.KAKUNA, "Kakuna");
        translationBuilder.add(PokemonGen1Photos.BEEDRILL, "Beedrill");
        translationBuilder.add(PokemonGen1Photos.PIDGEY, "Pidgey");
        translationBuilder.add(PokemonGen1Photos.PIDGEOTTO, "Pidgeotto");
        translationBuilder.add(PokemonGen1Photos.PIDGEOT, "Pidgeot");
        translationBuilder.add(PokemonGen1Photos.RATTATA, "Rattata");
        translationBuilder.add(PokemonGen1Photos.RATICATE, "Raticate");
        translationBuilder.add(PokemonGen1Photos.SPEAROW, "Spearow");
        translationBuilder.add(PokemonGen1Photos.FEAROW, "Fearow");
        translationBuilder.add(PokemonGen1Photos.EKANS, "Ekans");
        translationBuilder.add(PokemonGen1Photos.ARBOK, "Arbok");
        translationBuilder.add(PokemonGen1Photos.PIKACHU, "Pikachu");
        translationBuilder.add(PokemonGen1Photos.RAICHU, "Raichu");
        translationBuilder.add(PokemonGen1Photos.SANDSHREW, "Sandshrew");
        translationBuilder.add(PokemonGen1Photos.SANDSLASH, "Sandslash");
        translationBuilder.add(PokemonGen1Photos.NIDORAN_FEMALE, "Nidoran Female");
        translationBuilder.add(PokemonGen1Photos.NIDORINA, "Nidorina");
        translationBuilder.add(PokemonGen1Photos.NIDOQUEEN, "Nidoqueen");
        translationBuilder.add(PokemonGen1Photos.NIDORAN_MALE, "Nidoran Male");
        translationBuilder.add(PokemonGen1Photos.NIDORINO, "Nidorino");
        translationBuilder.add(PokemonGen1Photos.NIDOKING, "Nidoking");
        translationBuilder.add(PokemonGen1Photos.CLEFAIRY, "Clefairy");
        translationBuilder.add(PokemonGen1Photos.CLEFABLE, "Clefable");
        translationBuilder.add(PokemonGen1Photos.VULPIX, "Vulpix");
        translationBuilder.add(PokemonGen1Photos.NINETALES, "Ninetales");
        translationBuilder.add(PokemonGen1Photos.JIGGLYPUFF, "Jigglypuff");
        translationBuilder.add(PokemonGen1Photos.WIGGLYTUFF, "Wigglytuff");
        translationBuilder.add(PokemonGen1Photos.ZUBAT, "Zubat");
        translationBuilder.add(PokemonGen1Photos.GOLBAT, "Golbat");
        translationBuilder.add(PokemonGen1Photos.ODDISH, "Oddish");
        translationBuilder.add(PokemonGen1Photos.GLOOM, "Gloom");
        translationBuilder.add(PokemonGen1Photos.VILEPLUME, "Vileplume");
        translationBuilder.add(PokemonGen1Photos.PARAS, "Paras");
        translationBuilder.add(PokemonGen1Photos.PARASECT, "Parasect");
        translationBuilder.add(PokemonGen1Photos.VENONAT, "Venonat");
        translationBuilder.add(PokemonGen1Photos.VENOMOTH, "Venomoth");
        translationBuilder.add(PokemonGen1Photos.DIGLETT, "Diglett");
        translationBuilder.add(PokemonGen1Photos.DUGTRIO, "Dugtrio");
        translationBuilder.add(PokemonGen1Photos.MEOWTH, "Meowth");
        translationBuilder.add(PokemonGen1Photos.PERSIAN, "Persian");
        translationBuilder.add(PokemonGen1Photos.PSYDUCK, "Psyduck");
        translationBuilder.add(PokemonGen1Photos.GOLDUCK, "Golduck");
        translationBuilder.add(PokemonGen1Photos.MANKEY, "Mankey");
        translationBuilder.add(PokemonGen1Photos.PRIMEAPE, "Primeape");
        translationBuilder.add(PokemonGen1Photos.GROWLITHE, "Growlithe");
        translationBuilder.add(PokemonGen1Photos.ARCANINE, "Arcanine");
        translationBuilder.add(PokemonGen1Photos.POLIWAG, "Poliwag");
        translationBuilder.add(PokemonGen1Photos.POLIWHIRL, "Poliwhirl");
        translationBuilder.add(PokemonGen1Photos.POLIWRATH, "Poliwrath");
        translationBuilder.add(PokemonGen1Photos.ABRA, "Abra");
        translationBuilder.add(PokemonGen1Photos.KADABRA, "Kadabra");
        translationBuilder.add(PokemonGen1Photos.ALAKAZAM, "Alakazam");
        translationBuilder.add(PokemonGen1Photos.MACHOP, "Machop");
        translationBuilder.add(PokemonGen1Photos.MACHOKE, "Machoke");
        translationBuilder.add(PokemonGen1Photos.MACHAMP, "Machamp");
        translationBuilder.add(PokemonGen1Photos.BELLSPROUT, "Bellsprout");
        translationBuilder.add(PokemonGen1Photos.WEEPINBELL, "Weepinbell");
        translationBuilder.add(PokemonGen1Photos.VICTREEBEL, "Victreebel");
        translationBuilder.add(PokemonGen1Photos.TENTACOOL, "Tentacool");
        translationBuilder.add(PokemonGen1Photos.TENTACRUEL, "Tentacruel");
        translationBuilder.add(PokemonGen1Photos.GEODUDE, "Geodude");
        translationBuilder.add(PokemonGen1Photos.GRAVELER, "Graveler");
        translationBuilder.add(PokemonGen1Photos.GOLEM, "Golem");
        translationBuilder.add(PokemonGen1Photos.PONYTA, "Ponyta");
        translationBuilder.add(PokemonGen1Photos.RAPIDASH, "Rapidash");
        translationBuilder.add(PokemonGen1Photos.SLOWPOKE, "Slowpoke");
        translationBuilder.add(PokemonGen1Photos.SLOWBRO, "Slowbro");
        translationBuilder.add(PokemonGen1Photos.MAGNEMITE, "Magnemite");
        translationBuilder.add(PokemonGen1Photos.MAGNETON, "Magneton");
        translationBuilder.add(PokemonGen1Photos.FARFETCHD, "Farfetch'd");
        translationBuilder.add(PokemonGen1Photos.DODUO, "Doduo");
        translationBuilder.add(PokemonGen1Photos.DODRIO, "Dodrio");
        translationBuilder.add(PokemonGen1Photos.SEEL, "Seel");
        translationBuilder.add(PokemonGen1Photos.DEWGONG, "Dewgong");
        translationBuilder.add(PokemonGen1Photos.GRIMER, "Grimer");
        translationBuilder.add(PokemonGen1Photos.MUK, "Muk");
        translationBuilder.add(PokemonGen1Photos.SHELLDER, "Shellder");
        translationBuilder.add(PokemonGen1Photos.CLOYSTER, "Cloyster");
        translationBuilder.add(PokemonGen1Photos.GASTLY, "Gastly");
        translationBuilder.add(PokemonGen1Photos.HAUNTER, "Haunter");
        translationBuilder.add(PokemonGen1Photos.GENGAR, "Gengar");
        translationBuilder.add(PokemonGen1Photos.ONIX, "Onix");
        translationBuilder.add(PokemonGen1Photos.DROWZEE, "Drowzee");
        translationBuilder.add(PokemonGen1Photos.HYPNO, "Hypno");
        translationBuilder.add(PokemonGen1Photos.KRABBY, "Krabby");
        translationBuilder.add(PokemonGen1Photos.KINGLER, "Kingler");
        translationBuilder.add(PokemonGen1Photos.VOLTORB, "Voltorb");
        translationBuilder.add(PokemonGen1Photos.ELECTRODE, "Electrode");
        translationBuilder.add(PokemonGen1Photos.EXEGGCUTE, "Exeggcute");
        translationBuilder.add(PokemonGen1Photos.EXEGGUTOR, "Exeggutor");
        translationBuilder.add(PokemonGen1Photos.CUBONE, "Cubone");
        translationBuilder.add(PokemonGen1Photos.MAROWAK, "Marowak");
        translationBuilder.add(PokemonGen1Photos.HITMONLEE, "Hitmonlee");
        translationBuilder.add(PokemonGen1Photos.HITMONCHAN, "Hitmonchan");
        translationBuilder.add(PokemonGen1Photos.LICKITUNG, "Lickitung");
        translationBuilder.add(PokemonGen1Photos.KOFFING, "Koffing");
        translationBuilder.add(PokemonGen1Photos.WEEZING, "Weezing");
        translationBuilder.add(PokemonGen1Photos.RHYHORN, "Rhyhorn");
        translationBuilder.add(PokemonGen1Photos.RHYDON, "Rhydon");
        translationBuilder.add(PokemonGen1Photos.CHANSEY, "Chansey");
        translationBuilder.add(PokemonGen1Photos.TANGELA, "Tangela");
        translationBuilder.add(PokemonGen1Photos.KANGASKHAN, "Kangaskhan");
        translationBuilder.add(PokemonGen1Photos.HORSEA, "Horsea");
        translationBuilder.add(PokemonGen1Photos.SEADRA, "Seadra");
        translationBuilder.add(PokemonGen1Photos.GOLDEEN, "Goldeen");
        translationBuilder.add(PokemonGen1Photos.SEAKING, "Seaking");
        translationBuilder.add(PokemonGen1Photos.STARYU, "Staryu");
        translationBuilder.add(PokemonGen1Photos.STARMIE, "Starmie");
        translationBuilder.add(PokemonGen1Photos.MR_MIME, "Mr.Mime");
        translationBuilder.add(PokemonGen1Photos.SCYTHER, "Scyther");
        translationBuilder.add(PokemonGen1Photos.JYNX, "Jynx");
        translationBuilder.add(PokemonGen1Photos.ELECTABUZZ, "Electabuzz");
        translationBuilder.add(PokemonGen1Photos.MAGMAR, "Magmar");
        translationBuilder.add(PokemonGen1Photos.PINSIR, "Pinsir");
        translationBuilder.add(PokemonGen1Photos.TAUROS, "Tauros");
        translationBuilder.add(PokemonGen1Photos.MAGIKARP, "Magikarp");
        translationBuilder.add(PokemonGen1Photos.GYARADOS, "Gyarados");
        translationBuilder.add(PokemonGen1Photos.LAPRAS, "Lapras");
        translationBuilder.add(PokemonGen1Photos.DITTO, "Ditto");
        translationBuilder.add(PokemonGen1Photos.EEVEE, "Eevee");
        translationBuilder.add(PokemonGen1Photos.VAPOREON, "Vaporeon");
        translationBuilder.add(PokemonGen1Photos.JOLTEON, "Jolteon");
        translationBuilder.add(PokemonGen1Photos.FLAREON, "Flareon");
        translationBuilder.add(PokemonGen1Photos.PORYGON, "Porygon");
        translationBuilder.add(PokemonGen1Photos.OMANYTE, "Omanyte");
        translationBuilder.add(PokemonGen1Photos.OMASTAR, "Omastar");
        translationBuilder.add(PokemonGen1Photos.KABUTO, "Kabuto");
        translationBuilder.add(PokemonGen1Photos.KABUTOPS, "Kabutops");
        translationBuilder.add(PokemonGen1Photos.AERODACTYL, "Aerodactyl");
        translationBuilder.add(PokemonGen1Photos.SNORLAX, "Snorlax");
        translationBuilder.add(PokemonGen1Photos.ARTICUNO, "Articuno");
        translationBuilder.add(PokemonGen1Photos.ZAPDOS, "Zapdos");
        translationBuilder.add(PokemonGen1Photos.MOLTRES, "Moltres");
        translationBuilder.add(PokemonGen1Photos.DRATINI, "Dratini");
        translationBuilder.add(PokemonGen1Photos.DRAGONAIR, "Dragonair");
        translationBuilder.add(PokemonGen1Photos.DRAGONITE, "Dragonite");
        translationBuilder.add(PokemonGen1Photos.MEWTWO, "Mewtwo");
        translationBuilder.add(PokemonGen1Photos.MEW, "Mew");
        // gen 1 shiny
        translationBuilder.add(PokemonGen1Photos.BULBASAUR_SHINY, "Bulbasaur Shiny");
        translationBuilder.add(PokemonGen1Photos.IVYSAUR_SHINY, "Ivysaur Shiny");
        translationBuilder.add(PokemonGen1Photos.VENUSAUR_SHINY, "Venusaur Shiny");
        translationBuilder.add(PokemonGen1Photos.CHARMANDER_SHINY, "Charmander Shiny");
        translationBuilder.add(PokemonGen1Photos.CHARMELEON_SHINY, "Charmeleon Shiny");
        translationBuilder.add(PokemonGen1Photos.CHARIZARD_SHINY, "Charizard Shiny");
        translationBuilder.add(PokemonGen1Photos.SQUIRTLE_SHINY, "Squirtle Shiny");
        translationBuilder.add(PokemonGen1Photos.WARTORTLE_SHINY, "Wartortle Shiny");
        translationBuilder.add(PokemonGen1Photos.BLASTOISE_SHINY, "Blastoise Shiny");
        translationBuilder.add(PokemonGen1Photos.CATERPIE_SHINY, "Caterpie Shiny");
        translationBuilder.add(PokemonGen1Photos.METAPOD_SHINY, "Metapod Shiny");
        translationBuilder.add(PokemonGen1Photos.BUTTERFREE_SHINY, "Butterfree Shiny");
        translationBuilder.add(PokemonGen1Photos.WEEDLE_SHINY, "Weedle Shiny");
        translationBuilder.add(PokemonGen1Photos.KAKUNA_SHINY, "Kakuna Shiny");
        translationBuilder.add(PokemonGen1Photos.BEEDRILL_SHINY, "Beedrill Shiny");
        translationBuilder.add(PokemonGen1Photos.PIDGEY_SHINY, "Pidgey Shiny");
        translationBuilder.add(PokemonGen1Photos.PIDGEOTTO_SHINY, "Pidgeotto Shiny");
        translationBuilder.add(PokemonGen1Photos.PIDGEOT_SHINY, "Pidgeot Shiny");
        translationBuilder.add(PokemonGen1Photos.RATTATA_SHINY, "Rattata Shiny");
        translationBuilder.add(PokemonGen1Photos.RATICATE_SHINY, "Raticate Shiny");
        translationBuilder.add(PokemonGen1Photos.SPEAROW_SHINY, "Spearow Shiny");
        translationBuilder.add(PokemonGen1Photos.FEAROW_SHINY, "Fearow Shiny");
        translationBuilder.add(PokemonGen1Photos.EKANS_SHINY, "Ekans Shiny");
        translationBuilder.add(PokemonGen1Photos.ARBOK_SHINY, "Arbok Shiny");
        translationBuilder.add(PokemonGen1Photos.PIKACHU_SHINY, "Pikachu Shiny");
        translationBuilder.add(PokemonGen1Photos.RAICHU_SHINY, "Raichu Shiny");
        translationBuilder.add(PokemonGen1Photos.SANDSHREW_SHINY, "Sandshrew Shiny");
        translationBuilder.add(PokemonGen1Photos.SANDSLASH_SHINY, "Sandslash Shiny");
        translationBuilder.add(PokemonGen1Photos.NIDORAN_FEMALE_SHINY, "Nidoran Female Shiny");
        translationBuilder.add(PokemonGen1Photos.NIDORINA_SHINY, "Nidorina Shiny");
        translationBuilder.add(PokemonGen1Photos.NIDOQUEEN_SHINY, "Nidoqueen Shiny");
        translationBuilder.add(PokemonGen1Photos.NIDORAN_MALE_SHINY, "Nidoran Male Shiny");
        translationBuilder.add(PokemonGen1Photos.NIDORINO_SHINY, "Nidorino Shiny");
        translationBuilder.add(PokemonGen1Photos.NIDOKING_SHINY, "Nidoking Shiny");
        translationBuilder.add(PokemonGen1Photos.CLEFAIRY_SHINY, "Clefairy Shiny");
        translationBuilder.add(PokemonGen1Photos.CLEFABLE_SHINY, "Clefable Shiny");
        translationBuilder.add(PokemonGen1Photos.VULPIX_SHINY, "Vulpix Shiny");
        translationBuilder.add(PokemonGen1Photos.NINETALES_SHINY, "Ninetales Shiny");
        translationBuilder.add(PokemonGen1Photos.JIGGLYPUFF_SHINY, "Jigglypuff Shiny");
        translationBuilder.add(PokemonGen1Photos.WIGGLYTUFF_SHINY, "Wigglytuff Shiny");
        translationBuilder.add(PokemonGen1Photos.ZUBAT_SHINY, "Zubat Shiny");
        translationBuilder.add(PokemonGen1Photos.GOLBAT_SHINY, "Golbat Shiny");
        translationBuilder.add(PokemonGen1Photos.ODDISH_SHINY, "Oddish Shiny");
        translationBuilder.add(PokemonGen1Photos.GLOOM_SHINY, "Gloom Shiny");
        translationBuilder.add(PokemonGen1Photos.VILEPLUME_SHINY, "Vileplume Shiny");
        translationBuilder.add(PokemonGen1Photos.PARAS_SHINY, "Paras Shiny");
        translationBuilder.add(PokemonGen1Photos.PARASECT_SHINY, "Parasect Shiny");
        translationBuilder.add(PokemonGen1Photos.VENONAT_SHINY, "Venonat Shiny");
        translationBuilder.add(PokemonGen1Photos.VENOMOTH_SHINY, "Venomoth Shiny");
        translationBuilder.add(PokemonGen1Photos.DIGLETT_SHINY, "Diglett Shiny");
        translationBuilder.add(PokemonGen1Photos.DUGTRIO_SHINY, "Dugtrio Shiny");
        translationBuilder.add(PokemonGen1Photos.MEOWTH_SHINY, "Meowth Shiny");
        translationBuilder.add(PokemonGen1Photos.PERSIAN_SHINY, "Persian Shiny");
        translationBuilder.add(PokemonGen1Photos.PSYDUCK_SHINY, "Psyduck Shiny");
        translationBuilder.add(PokemonGen1Photos.GOLDUCK_SHINY, "Golduck Shiny");
        translationBuilder.add(PokemonGen1Photos.MANKEY_SHINY, "Mankey Shiny");
        translationBuilder.add(PokemonGen1Photos.PRIMEAPE_SHINY, "Primeape Shiny");
        translationBuilder.add(PokemonGen1Photos.GROWLITHE_SHINY, "Growlithe Shiny");
        translationBuilder.add(PokemonGen1Photos.ARCANINE_SHINY, "Arcanine Shiny");
        translationBuilder.add(PokemonGen1Photos.POLIWAG_SHINY, "Poliwag Shiny");
        translationBuilder.add(PokemonGen1Photos.POLIWHIRL_SHINY, "Poliwhirl Shiny");
        translationBuilder.add(PokemonGen1Photos.POLIWRATH_SHINY, "Poliwrath Shiny");
        translationBuilder.add(PokemonGen1Photos.ABRA_SHINY, "Abra Shiny");
        translationBuilder.add(PokemonGen1Photos.KADABRA_SHINY, "Kadabra Shiny");
        translationBuilder.add(PokemonGen1Photos.ALAKAZAM_SHINY, "Alakazam Shiny");
        translationBuilder.add(PokemonGen1Photos.MACHOP_SHINY, "Machop Shiny");
        translationBuilder.add(PokemonGen1Photos.MACHOKE_SHINY, "Machoke Shiny");
        translationBuilder.add(PokemonGen1Photos.MACHAMP_SHINY, "Machamp Shiny");
        translationBuilder.add(PokemonGen1Photos.BELLSPROUT_SHINY, "Bellsprout Shiny");
        translationBuilder.add(PokemonGen1Photos.WEEPINBELL_SHINY, "Weepinbell Shiny");
        translationBuilder.add(PokemonGen1Photos.VICTREEBEL_SHINY, "Victreebel Shiny");
        translationBuilder.add(PokemonGen1Photos.TENTACOOL_SHINY, "Tentacool Shiny");
        translationBuilder.add(PokemonGen1Photos.TENTACRUEL_SHINY, "Tentacruel Shiny");
        translationBuilder.add(PokemonGen1Photos.GEODUDE_SHINY, "Geodude Shiny");
        translationBuilder.add(PokemonGen1Photos.GRAVELER_SHINY, "Graveler Shiny");
        translationBuilder.add(PokemonGen1Photos.GOLEM_SHINY, "Golem Shiny");
        translationBuilder.add(PokemonGen1Photos.PONYTA_SHINY, "Ponyta Shiny");
        translationBuilder.add(PokemonGen1Photos.RAPIDASH_SHINY, "Rapidash Shiny");
        translationBuilder.add(PokemonGen1Photos.SLOWPOKE_SHINY, "Slowpoke Shiny");
        translationBuilder.add(PokemonGen1Photos.SLOWBRO_SHINY, "Slowbro Shiny");
        translationBuilder.add(PokemonGen1Photos.MAGNEMITE_SHINY, "Magnemite Shiny");
        translationBuilder.add(PokemonGen1Photos.MAGNETON_SHINY, "Magneton Shiny");
        translationBuilder.add(PokemonGen1Photos.FARFETCHD_SHINY, "Farfetch'd Shiny");
        translationBuilder.add(PokemonGen1Photos.DODUO_SHINY, "Doduo Shiny");
        translationBuilder.add(PokemonGen1Photos.DODRIO_SHINY, "Dodrio Shiny");
        translationBuilder.add(PokemonGen1Photos.SEEL_SHINY, "Seel Shiny");
        translationBuilder.add(PokemonGen1Photos.DEWGONG_SHINY, "Dewgong Shiny");
        translationBuilder.add(PokemonGen1Photos.GRIMER_SHINY, "Grimer Shiny");
        translationBuilder.add(PokemonGen1Photos.MUK_SHINY, "Muk Shiny");
        translationBuilder.add(PokemonGen1Photos.SHELLDER_SHINY, "Shellder Shiny");
        translationBuilder.add(PokemonGen1Photos.CLOYSTER_SHINY, "Cloyster Shiny");
        translationBuilder.add(PokemonGen1Photos.GASTLY_SHINY, "Gastly Shiny");
        translationBuilder.add(PokemonGen1Photos.HAUNTER_SHINY, "Haunter Shiny");
        translationBuilder.add(PokemonGen1Photos.GENGAR_SHINY, "Gengar Shiny");
        translationBuilder.add(PokemonGen1Photos.ONIX_SHINY, "Onix Shiny");
        translationBuilder.add(PokemonGen1Photos.DROWZEE_SHINY, "Drowzee Shiny");
        translationBuilder.add(PokemonGen1Photos.HYPNO_SHINY, "Hypno Shiny");
        translationBuilder.add(PokemonGen1Photos.KRABBY_SHINY, "Krabby Shiny");
        translationBuilder.add(PokemonGen1Photos.KINGLER_SHINY, "Kingler Shiny");
        translationBuilder.add(PokemonGen1Photos.VOLTORB_SHINY, "Voltorb Shiny");
        translationBuilder.add(PokemonGen1Photos.ELECTRODE_SHINY, "Electrode Shiny");
        translationBuilder.add(PokemonGen1Photos.EXEGGCUTE_SHINY, "Exeggcute Shiny");
        translationBuilder.add(PokemonGen1Photos.EXEGGUTOR_SHINY, "Exeggutor Shiny");
        translationBuilder.add(PokemonGen1Photos.CUBONE_SHINY, "Cubone Shiny");
        translationBuilder.add(PokemonGen1Photos.MAROWAK_SHINY, "Marowak Shiny");
        translationBuilder.add(PokemonGen1Photos.HITMONLEE_SHINY, "Hitmonlee Shiny");
        translationBuilder.add(PokemonGen1Photos.HITMONCHAN_SHINY, "Hitmonchan Shiny");
        translationBuilder.add(PokemonGen1Photos.LICKITUNG_SHINY, "Lickitung Shiny");
        translationBuilder.add(PokemonGen1Photos.KOFFING_SHINY, "Koffing Shiny");
        translationBuilder.add(PokemonGen1Photos.WEEZING_SHINY, "Weezing Shiny");
        translationBuilder.add(PokemonGen1Photos.RHYHORN_SHINY, "Rhyhorn Shiny");
        translationBuilder.add(PokemonGen1Photos.RHYDON_SHINY, "Rhydon Shiny");
        translationBuilder.add(PokemonGen1Photos.CHANSEY_SHINY, "Chansey Shiny");
        translationBuilder.add(PokemonGen1Photos.TANGELA_SHINY, "Tangela Shiny");
        translationBuilder.add(PokemonGen1Photos.KANGASKHAN_SHINY, "Kangaskhan Shiny");
        translationBuilder.add(PokemonGen1Photos.HORSEA_SHINY, "Horsea Shiny");
        translationBuilder.add(PokemonGen1Photos.SEADRA_SHINY, "Seadra Shiny");
        translationBuilder.add(PokemonGen1Photos.GOLDEEN_SHINY, "Goldeen Shiny");
        translationBuilder.add(PokemonGen1Photos.SEAKING_SHINY, "Seaking Shiny");
        translationBuilder.add(PokemonGen1Photos.STARYU_SHINY, "Staryu Shiny");
        translationBuilder.add(PokemonGen1Photos.STARMIE_SHINY, "Starmie Shiny");
        translationBuilder.add(PokemonGen1Photos.MR_MIME_SHINY, "Mr.Mime Shiny");
        translationBuilder.add(PokemonGen1Photos.SCYTHER_SHINY, "Scyther Shiny");
        translationBuilder.add(PokemonGen1Photos.JYNX_SHINY, "Jynx Shiny");
        translationBuilder.add(PokemonGen1Photos.ELECTABUZZ_SHINY, "Electabuzz Shiny");
        translationBuilder.add(PokemonGen1Photos.MAGMAR_SHINY, "Magmar Shiny");
        translationBuilder.add(PokemonGen1Photos.PINSIR_SHINY, "Pinsir Shiny");
        translationBuilder.add(PokemonGen1Photos.TAUROS_SHINY, "Tauros Shiny");
        translationBuilder.add(PokemonGen1Photos.MAGIKARP_SHINY, "Magikarp Shiny");
        translationBuilder.add(PokemonGen1Photos.GYARADOS_SHINY, "Gyarados Shiny");
        translationBuilder.add(PokemonGen1Photos.LAPRAS_SHINY, "Lapras Shiny");
        translationBuilder.add(PokemonGen1Photos.DITTO_SHINY, "Ditto Shiny");
        translationBuilder.add(PokemonGen1Photos.EEVEE_SHINY, "Eevee Shiny");
        translationBuilder.add(PokemonGen1Photos.VAPOREON_SHINY, "Vaporeon Shiny");
        translationBuilder.add(PokemonGen1Photos.JOLTEON_SHINY, "Jolteon Shiny");
        translationBuilder.add(PokemonGen1Photos.FLAREON_SHINY, "Flareon Shiny");
        translationBuilder.add(PokemonGen1Photos.PORYGON_SHINY, "Porygon Shiny");
        translationBuilder.add(PokemonGen1Photos.OMANYTE_SHINY, "Omanyte Shiny");
        translationBuilder.add(PokemonGen1Photos.OMASTAR_SHINY, "Omastar Shiny");
        translationBuilder.add(PokemonGen1Photos.KABUTO_SHINY, "Kabuto Shiny");
        translationBuilder.add(PokemonGen1Photos.KABUTOPS_SHINY, "Kabutops Shiny");
        translationBuilder.add(PokemonGen1Photos.AERODACTYL_SHINY, "Aerodactyl Shiny");
        translationBuilder.add(PokemonGen1Photos.SNORLAX_SHINY, "Snorlax Shiny");
        translationBuilder.add(PokemonGen1Photos.ARTICUNO_SHINY, "Articuno Shiny");
        translationBuilder.add(PokemonGen1Photos.ZAPDOS_SHINY, "Zapdos Shiny");
        translationBuilder.add(PokemonGen1Photos.MOLTRES_SHINY, "Moltres Shiny");
        translationBuilder.add(PokemonGen1Photos.DRATINI_SHINY, "Dratini Shiny");
        translationBuilder.add(PokemonGen1Photos.DRAGONAIR_SHINY, "Dragonair Shiny");
        translationBuilder.add(PokemonGen1Photos.DRAGONITE_SHINY, "Dragonite Shiny");
        translationBuilder.add(PokemonGen1Photos.MEWTWO_SHINY, "Mewtwo Shiny");
        translationBuilder.add(PokemonGen1Photos.MEW_SHINY, "Mew Shiny");
    }
}
