package com.rainlsilica.datagen;

import com.rainlsilica.item.PokemonGen1Photos;
import com.rainlsilica.item.PokemonGen2Photos;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.minecraft.registry.RegistryWrapper;

import java.util.concurrent.CompletableFuture;

public class ModENUSLangProvider extends FabricLanguageProvider {
    public ModENUSLangProvider(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput, registryLookup);
    }

    @Override
    public void generateTranslations(RegistryWrapper.WrapperLookup wrapperLookup, TranslationBuilder translationBuilder) {
        translationBuilder.add("itemGroup.pokemon_photo", "Pokemon Photo");
        genOne(translationBuilder);
        genTwo(translationBuilder);

    }

    private void genOne(TranslationBuilder translationBuilder) {
        // gen 1 normal
        translationBuilder.add(PokemonGen1Photos.BULBASAUR, "Bulbasaur");
        translationBuilder.add(PokemonGen1Photos.IVYSAUR, "Ivysaur");
        translationBuilder.add(PokemonGen1Photos.VENUSAUR, "Venusaur");
        translationBuilder.add(PokemonGen1Photos.CHARMANDER, "Charmander");
        translationBuilder.add(PokemonGen1Photos.CHARMELEON, "Charmeleon");
        translationBuilder.add(PokemonGen1Photos.CHARIZARD, "Charizard");
        translationBuilder.add(PokemonGen1Photos.SQUIRTLE, "Squirtle");
        translationBuilder.add(PokemonGen1Photos.WARTORTLE, "Wartortle");
        translationBuilder.add(PokemonGen1Photos.BLASTOISE, "Blastoise");
        translationBuilder.add(PokemonGen1Photos.CATERPIE, "Caterpie");
        translationBuilder.add(PokemonGen1Photos.METAPOD, "Metapod");
        translationBuilder.add(PokemonGen1Photos.BUTTERFREE, "Butterfree");
        translationBuilder.add(PokemonGen1Photos.WEEDLE, "Weedle");
        translationBuilder.add(PokemonGen1Photos.KAKUNA, "Kakuna");
        translationBuilder.add(PokemonGen1Photos.BEEDRILL, "Beedrill");
        translationBuilder.add(PokemonGen1Photos.PIDGEY, "Pidgey");
        translationBuilder.add(PokemonGen1Photos.PIDGEOTTO, "Pidgeotto");
        translationBuilder.add(PokemonGen1Photos.PIDGEOT, "Pidgeot");
        translationBuilder.add(PokemonGen1Photos.RATTATA, "Rattata");
        translationBuilder.add(PokemonGen1Photos.RATICATE, "Raticate");
        translationBuilder.add(PokemonGen1Photos.SPEAROW, "Spearow");
        translationBuilder.add(PokemonGen1Photos.FEAROW, "Fearow");
        translationBuilder.add(PokemonGen1Photos.EKANS, "Ekans");
        translationBuilder.add(PokemonGen1Photos.ARBOK, "Arbok");
        translationBuilder.add(PokemonGen1Photos.PIKACHU, "Pikachu");
        translationBuilder.add(PokemonGen1Photos.RAICHU, "Raichu");
        translationBuilder.add(PokemonGen1Photos.SANDSHREW, "Sandshrew");
        translationBuilder.add(PokemonGen1Photos.SANDSLASH, "Sandslash");
        translationBuilder.add(PokemonGen1Photos.NIDORAN_FEMALE, "Nidoran Female");
        translationBuilder.add(PokemonGen1Photos.NIDORINA, "Nidorina");
        translationBuilder.add(PokemonGen1Photos.NIDOQUEEN, "Nidoqueen");
        translationBuilder.add(PokemonGen1Photos.NIDORAN_MALE, "Nidoran Male");
        translationBuilder.add(PokemonGen1Photos.NIDORINO, "Nidorino");
        translationBuilder.add(PokemonGen1Photos.NIDOKING, "Nidoking");
        translationBuilder.add(PokemonGen1Photos.CLEFAIRY, "Clefairy");
        translationBuilder.add(PokemonGen1Photos.CLEFABLE, "Clefable");
        translationBuilder.add(PokemonGen1Photos.VULPIX, "Vulpix");
        translationBuilder.add(PokemonGen1Photos.NINETALES, "Ninetales");
        translationBuilder.add(PokemonGen1Photos.JIGGLYPUFF, "Jigglypuff");
        translationBuilder.add(PokemonGen1Photos.WIGGLYTUFF, "Wigglytuff");
        translationBuilder.add(PokemonGen1Photos.ZUBAT, "Zubat");
        translationBuilder.add(PokemonGen1Photos.GOLBAT, "Golbat");
        translationBuilder.add(PokemonGen1Photos.ODDISH, "Oddish");
        translationBuilder.add(PokemonGen1Photos.GLOOM, "Gloom");
        translationBuilder.add(PokemonGen1Photos.VILEPLUME, "Vileplume");
        translationBuilder.add(PokemonGen1Photos.PARAS, "Paras");
        translationBuilder.add(PokemonGen1Photos.PARASECT, "Parasect");
        translationBuilder.add(PokemonGen1Photos.VENONAT, "Venonat");
        translationBuilder.add(PokemonGen1Photos.VENOMOTH, "Venomoth");
        translationBuilder.add(PokemonGen1Photos.DIGLETT, "Diglett");
        translationBuilder.add(PokemonGen1Photos.DUGTRIO, "Dugtrio");
        translationBuilder.add(PokemonGen1Photos.MEOWTH, "Meowth");
        translationBuilder.add(PokemonGen1Photos.PERSIAN, "Persian");
        translationBuilder.add(PokemonGen1Photos.PSYDUCK, "Psyduck");
        translationBuilder.add(PokemonGen1Photos.GOLDUCK, "Golduck");
        translationBuilder.add(PokemonGen1Photos.MANKEY, "Mankey");
        translationBuilder.add(PokemonGen1Photos.PRIMEAPE, "Primeape");
        translationBuilder.add(PokemonGen1Photos.GROWLITHE, "Growlithe");
        translationBuilder.add(PokemonGen1Photos.ARCANINE, "Arcanine");
        translationBuilder.add(PokemonGen1Photos.POLIWAG, "Poliwag");
        translationBuilder.add(PokemonGen1Photos.POLIWHIRL, "Poliwhirl");
        translationBuilder.add(PokemonGen1Photos.POLIWRATH, "Poliwrath");
        translationBuilder.add(PokemonGen1Photos.ABRA, "Abra");
        translationBuilder.add(PokemonGen1Photos.KADABRA, "Kadabra");
        translationBuilder.add(PokemonGen1Photos.ALAKAZAM, "Alakazam");
        translationBuilder.add(PokemonGen1Photos.MACHOP, "Machop");
        translationBuilder.add(PokemonGen1Photos.MACHOKE, "Machoke");
        translationBuilder.add(PokemonGen1Photos.MACHAMP, "Machamp");
        translationBuilder.add(PokemonGen1Photos.BELLSPROUT, "Bellsprout");
        translationBuilder.add(PokemonGen1Photos.WEEPINBELL, "Weepinbell");
        translationBuilder.add(PokemonGen1Photos.VICTREEBEL, "Victreebel");
        translationBuilder.add(PokemonGen1Photos.TENTACOOL, "Tentacool");
        translationBuilder.add(PokemonGen1Photos.TENTACRUEL, "Tentacruel");
        translationBuilder.add(PokemonGen1Photos.GEODUDE, "Geodude");
        translationBuilder.add(PokemonGen1Photos.GRAVELER, "Graveler");
        translationBuilder.add(PokemonGen1Photos.GOLEM, "Golem");
        translationBuilder.add(PokemonGen1Photos.PONYTA, "Ponyta");
        translationBuilder.add(PokemonGen1Photos.RAPIDASH, "Rapidash");
        translationBuilder.add(PokemonGen1Photos.SLOWPOKE, "Slowpoke");
        translationBuilder.add(PokemonGen1Photos.SLOWBRO, "Slowbro");
        translationBuilder.add(PokemonGen1Photos.MAGNEMITE, "Magnemite");
        translationBuilder.add(PokemonGen1Photos.MAGNETON, "Magneton");
        translationBuilder.add(PokemonGen1Photos.FARFETCHD, "Farfetch'd");
        translationBuilder.add(PokemonGen1Photos.DODUO, "Doduo");
        translationBuilder.add(PokemonGen1Photos.DODRIO, "Dodrio");
        translationBuilder.add(PokemonGen1Photos.SEEL, "Seel");
        translationBuilder.add(PokemonGen1Photos.DEWGONG, "Dewgong");
        translationBuilder.add(PokemonGen1Photos.GRIMER, "Grimer");
        translationBuilder.add(PokemonGen1Photos.MUK, "Muk");
        translationBuilder.add(PokemonGen1Photos.SHELLDER, "Shellder");
        translationBuilder.add(PokemonGen1Photos.CLOYSTER, "Cloyster");
        translationBuilder.add(PokemonGen1Photos.GASTLY, "Gastly");
        translationBuilder.add(PokemonGen1Photos.HAUNTER, "Haunter");
        translationBuilder.add(PokemonGen1Photos.GENGAR, "Gengar");
        translationBuilder.add(PokemonGen1Photos.ONIX, "Onix");
        translationBuilder.add(PokemonGen1Photos.DROWZEE, "Drowzee");
        translationBuilder.add(PokemonGen1Photos.HYPNO, "Hypno");
        translationBuilder.add(PokemonGen1Photos.KRABBY, "Krabby");
        translationBuilder.add(PokemonGen1Photos.KINGLER, "Kingler");
        translationBuilder.add(PokemonGen1Photos.VOLTORB, "Voltorb");
        translationBuilder.add(PokemonGen1Photos.ELECTRODE, "Electrode");
        translationBuilder.add(PokemonGen1Photos.EXEGGCUTE, "Exeggcute");
        translationBuilder.add(PokemonGen1Photos.EXEGGUTOR, "Exeggutor");
        translationBuilder.add(PokemonGen1Photos.CUBONE, "Cubone");
        translationBuilder.add(PokemonGen1Photos.MAROWAK, "Marowak");
        translationBuilder.add(PokemonGen1Photos.HITMONLEE, "Hitmonlee");
        translationBuilder.add(PokemonGen1Photos.HITMONCHAN, "Hitmonchan");
        translationBuilder.add(PokemonGen1Photos.LICKITUNG, "Lickitung");
        translationBuilder.add(PokemonGen1Photos.KOFFING, "Koffing");
        translationBuilder.add(PokemonGen1Photos.WEEZING, "Weezing");
        translationBuilder.add(PokemonGen1Photos.RHYHORN, "Rhyhorn");
        translationBuilder.add(PokemonGen1Photos.RHYDON, "Rhydon");
        translationBuilder.add(PokemonGen1Photos.CHANSEY, "Chansey");
        translationBuilder.add(PokemonGen1Photos.TANGELA, "Tangela");
        translationBuilder.add(PokemonGen1Photos.KANGASKHAN, "Kangaskhan");
        translationBuilder.add(PokemonGen1Photos.HORSEA, "Horsea");
        translationBuilder.add(PokemonGen1Photos.SEADRA, "Seadra");
        translationBuilder.add(PokemonGen1Photos.GOLDEEN, "Goldeen");
        translationBuilder.add(PokemonGen1Photos.SEAKING, "Seaking");
        translationBuilder.add(PokemonGen1Photos.STARYU, "Staryu");
        translationBuilder.add(PokemonGen1Photos.STARMIE, "Starmie");
        translationBuilder.add(PokemonGen1Photos.MR_MIME, "Mr.Mime");
        translationBuilder.add(PokemonGen1Photos.SCYTHER, "Scyther");
        translationBuilder.add(PokemonGen1Photos.JYNX, "Jynx");
        translationBuilder.add(PokemonGen1Photos.ELECTABUZZ, "Electabuzz");
        translationBuilder.add(PokemonGen1Photos.MAGMAR, "Magmar");
        translationBuilder.add(PokemonGen1Photos.PINSIR, "Pinsir");
        translationBuilder.add(PokemonGen1Photos.TAUROS, "Tauros");
        translationBuilder.add(PokemonGen1Photos.MAGIKARP, "Magikarp");
        translationBuilder.add(PokemonGen1Photos.GYARADOS, "Gyarados");
        translationBuilder.add(PokemonGen1Photos.LAPRAS, "Lapras");
        translationBuilder.add(PokemonGen1Photos.DITTO, "Ditto");
        translationBuilder.add(PokemonGen1Photos.EEVEE, "Eevee");
        translationBuilder.add(PokemonGen1Photos.VAPOREON, "Vaporeon");
        translationBuilder.add(PokemonGen1Photos.JOLTEON, "Jolteon");
        translationBuilder.add(PokemonGen1Photos.FLAREON, "Flareon");
        translationBuilder.add(PokemonGen1Photos.PORYGON, "Porygon");
        translationBuilder.add(PokemonGen1Photos.OMANYTE, "Omanyte");
        translationBuilder.add(PokemonGen1Photos.OMASTAR, "Omastar");
        translationBuilder.add(PokemonGen1Photos.KABUTO, "Kabuto");
        translationBuilder.add(PokemonGen1Photos.KABUTOPS, "Kabutops");
        translationBuilder.add(PokemonGen1Photos.AERODACTYL, "Aerodactyl");
        translationBuilder.add(PokemonGen1Photos.SNORLAX, "Snorlax");
        translationBuilder.add(PokemonGen1Photos.ARTICUNO, "Articuno");
        translationBuilder.add(PokemonGen1Photos.ZAPDOS, "Zapdos");
        translationBuilder.add(PokemonGen1Photos.MOLTRES, "Moltres");
        translationBuilder.add(PokemonGen1Photos.DRATINI, "Dratini");
        translationBuilder.add(PokemonGen1Photos.DRAGONAIR, "Dragonair");
        translationBuilder.add(PokemonGen1Photos.DRAGONITE, "Dragonite");
        translationBuilder.add(PokemonGen1Photos.MEWTWO, "Mewtwo");
        translationBuilder.add(PokemonGen1Photos.MEW, "Mew");
        // gen 1 shiny
        translationBuilder.add(PokemonGen1Photos.BULBASAUR_SHINY, "Bulbasaur Shiny");
        translationBuilder.add(PokemonGen1Photos.IVYSAUR_SHINY, "Ivysaur Shiny");
        translationBuilder.add(PokemonGen1Photos.VENUSAUR_SHINY, "Venusaur Shiny");
        translationBuilder.add(PokemonGen1Photos.CHARMANDER_SHINY, "Charmander Shiny");
        translationBuilder.add(PokemonGen1Photos.CHARMELEON_SHINY, "Charmeleon Shiny");
        translationBuilder.add(PokemonGen1Photos.CHARIZARD_SHINY, "Charizard Shiny");
        translationBuilder.add(PokemonGen1Photos.SQUIRTLE_SHINY, "Squirtle Shiny");
        translationBuilder.add(PokemonGen1Photos.WARTORTLE_SHINY, "Wartortle Shiny");
        translationBuilder.add(PokemonGen1Photos.BLASTOISE_SHINY, "Blastoise Shiny");
        translationBuilder.add(PokemonGen1Photos.CATERPIE_SHINY, "Caterpie Shiny");
        translationBuilder.add(PokemonGen1Photos.METAPOD_SHINY, "Metapod Shiny");
        translationBuilder.add(PokemonGen1Photos.BUTTERFREE_SHINY, "Butterfree Shiny");
        translationBuilder.add(PokemonGen1Photos.WEEDLE_SHINY, "Weedle Shiny");
        translationBuilder.add(PokemonGen1Photos.KAKUNA_SHINY, "Kakuna Shiny");
        translationBuilder.add(PokemonGen1Photos.BEEDRILL_SHINY, "Beedrill Shiny");
        translationBuilder.add(PokemonGen1Photos.PIDGEY_SHINY, "Pidgey Shiny");
        translationBuilder.add(PokemonGen1Photos.PIDGEOTTO_SHINY, "Pidgeotto Shiny");
        translationBuilder.add(PokemonGen1Photos.PIDGEOT_SHINY, "Pidgeot Shiny");
        translationBuilder.add(PokemonGen1Photos.RATTATA_SHINY, "Rattata Shiny");
        translationBuilder.add(PokemonGen1Photos.RATICATE_SHINY, "Raticate Shiny");
        translationBuilder.add(PokemonGen1Photos.SPEAROW_SHINY, "Spearow Shiny");
        translationBuilder.add(PokemonGen1Photos.FEAROW_SHINY, "Fearow Shiny");
        translationBuilder.add(PokemonGen1Photos.EKANS_SHINY, "Ekans Shiny");
        translationBuilder.add(PokemonGen1Photos.ARBOK_SHINY, "Arbok Shiny");
        translationBuilder.add(PokemonGen1Photos.PIKACHU_SHINY, "Pikachu Shiny");
        translationBuilder.add(PokemonGen1Photos.RAICHU_SHINY, "Raichu Shiny");
        translationBuilder.add(PokemonGen1Photos.SANDSHREW_SHINY, "Sandshrew Shiny");
        translationBuilder.add(PokemonGen1Photos.SANDSLASH_SHINY, "Sandslash Shiny");
        translationBuilder.add(PokemonGen1Photos.NIDORAN_FEMALE_SHINY, "Nidoran Female Shiny");
        translationBuilder.add(PokemonGen1Photos.NIDORINA_SHINY, "Nidorina Shiny");
        translationBuilder.add(PokemonGen1Photos.NIDOQUEEN_SHINY, "Nidoqueen Shiny");
        translationBuilder.add(PokemonGen1Photos.NIDORAN_MALE_SHINY, "Nidoran Male Shiny");
        translationBuilder.add(PokemonGen1Photos.NIDORINO_SHINY, "Nidorino Shiny");
        translationBuilder.add(PokemonGen1Photos.NIDOKING_SHINY, "Nidoking Shiny");
        translationBuilder.add(PokemonGen1Photos.CLEFAIRY_SHINY, "Clefairy Shiny");
        translationBuilder.add(PokemonGen1Photos.CLEFABLE_SHINY, "Clefable Shiny");
        translationBuilder.add(PokemonGen1Photos.VULPIX_SHINY, "Vulpix Shiny");
        translationBuilder.add(PokemonGen1Photos.NINETALES_SHINY, "Ninetales Shiny");
        translationBuilder.add(PokemonGen1Photos.JIGGLYPUFF_SHINY, "Jigglypuff Shiny");
        translationBuilder.add(PokemonGen1Photos.WIGGLYTUFF_SHINY, "Wigglytuff Shiny");
        translationBuilder.add(PokemonGen1Photos.ZUBAT_SHINY, "Zubat Shiny");
        translationBuilder.add(PokemonGen1Photos.GOLBAT_SHINY, "Golbat Shiny");
        translationBuilder.add(PokemonGen1Photos.ODDISH_SHINY, "Oddish Shiny");
        translationBuilder.add(PokemonGen1Photos.GLOOM_SHINY, "Gloom Shiny");
        translationBuilder.add(PokemonGen1Photos.VILEPLUME_SHINY, "Vileplume Shiny");
        translationBuilder.add(PokemonGen1Photos.PARAS_SHINY, "Paras Shiny");
        translationBuilder.add(PokemonGen1Photos.PARASECT_SHINY, "Parasect Shiny");
        translationBuilder.add(PokemonGen1Photos.VENONAT_SHINY, "Venonat Shiny");
        translationBuilder.add(PokemonGen1Photos.VENOMOTH_SHINY, "Venomoth Shiny");
        translationBuilder.add(PokemonGen1Photos.DIGLETT_SHINY, "Diglett Shiny");
        translationBuilder.add(PokemonGen1Photos.DUGTRIO_SHINY, "Dugtrio Shiny");
        translationBuilder.add(PokemonGen1Photos.MEOWTH_SHINY, "Meowth Shiny");
        translationBuilder.add(PokemonGen1Photos.PERSIAN_SHINY, "Persian Shiny");
        translationBuilder.add(PokemonGen1Photos.PSYDUCK_SHINY, "Psyduck Shiny");
        translationBuilder.add(PokemonGen1Photos.GOLDUCK_SHINY, "Golduck Shiny");
        translationBuilder.add(PokemonGen1Photos.MANKEY_SHINY, "Mankey Shiny");
        translationBuilder.add(PokemonGen1Photos.PRIMEAPE_SHINY, "Primeape Shiny");
        translationBuilder.add(PokemonGen1Photos.GROWLITHE_SHINY, "Growlithe Shiny");
        translationBuilder.add(PokemonGen1Photos.ARCANINE_SHINY, "Arcanine Shiny");
        translationBuilder.add(PokemonGen1Photos.POLIWAG_SHINY, "Poliwag Shiny");
        translationBuilder.add(PokemonGen1Photos.POLIWHIRL_SHINY, "Poliwhirl Shiny");
        translationBuilder.add(PokemonGen1Photos.POLIWRATH_SHINY, "Poliwrath Shiny");
        translationBuilder.add(PokemonGen1Photos.ABRA_SHINY, "Abra Shiny");
        translationBuilder.add(PokemonGen1Photos.KADABRA_SHINY, "Kadabra Shiny");
        translationBuilder.add(PokemonGen1Photos.ALAKAZAM_SHINY, "Alakazam Shiny");
        translationBuilder.add(PokemonGen1Photos.MACHOP_SHINY, "Machop Shiny");
        translationBuilder.add(PokemonGen1Photos.MACHOKE_SHINY, "Machoke Shiny");
        translationBuilder.add(PokemonGen1Photos.MACHAMP_SHINY, "Machamp Shiny");
        translationBuilder.add(PokemonGen1Photos.BELLSPROUT_SHINY, "Bellsprout Shiny");
        translationBuilder.add(PokemonGen1Photos.WEEPINBELL_SHINY, "Weepinbell Shiny");
        translationBuilder.add(PokemonGen1Photos.VICTREEBEL_SHINY, "Victreebel Shiny");
        translationBuilder.add(PokemonGen1Photos.TENTACOOL_SHINY, "Tentacool Shiny");
        translationBuilder.add(PokemonGen1Photos.TENTACRUEL_SHINY, "Tentacruel Shiny");
        translationBuilder.add(PokemonGen1Photos.GEODUDE_SHINY, "Geodude Shiny");
        translationBuilder.add(PokemonGen1Photos.GRAVELER_SHINY, "Graveler Shiny");
        translationBuilder.add(PokemonGen1Photos.GOLEM_SHINY, "Golem Shiny");
        translationBuilder.add(PokemonGen1Photos.PONYTA_SHINY, "Ponyta Shiny");
        translationBuilder.add(PokemonGen1Photos.RAPIDASH_SHINY, "Rapidash Shiny");
        translationBuilder.add(PokemonGen1Photos.SLOWPOKE_SHINY, "Slowpoke Shiny");
        translationBuilder.add(PokemonGen1Photos.SLOWBRO_SHINY, "Slowbro Shiny");
        translationBuilder.add(PokemonGen1Photos.MAGNEMITE_SHINY, "Magnemite Shiny");
        translationBuilder.add(PokemonGen1Photos.MAGNETON_SHINY, "Magneton Shiny");
        translationBuilder.add(PokemonGen1Photos.FARFETCHD_SHINY, "Farfetch'd Shiny");
        translationBuilder.add(PokemonGen1Photos.DODUO_SHINY, "Doduo Shiny");
        translationBuilder.add(PokemonGen1Photos.DODRIO_SHINY, "Dodrio Shiny");
        translationBuilder.add(PokemonGen1Photos.SEEL_SHINY, "Seel Shiny");
        translationBuilder.add(PokemonGen1Photos.DEWGONG_SHINY, "Dewgong Shiny");
        translationBuilder.add(PokemonGen1Photos.GRIMER_SHINY, "Grimer Shiny");
        translationBuilder.add(PokemonGen1Photos.MUK_SHINY, "Muk Shiny");
        translationBuilder.add(PokemonGen1Photos.SHELLDER_SHINY, "Shellder Shiny");
        translationBuilder.add(PokemonGen1Photos.CLOYSTER_SHINY, "Cloyster Shiny");
        translationBuilder.add(PokemonGen1Photos.GASTLY_SHINY, "Gastly Shiny");
        translationBuilder.add(PokemonGen1Photos.HAUNTER_SHINY, "Haunter Shiny");
        translationBuilder.add(PokemonGen1Photos.GENGAR_SHINY, "Gengar Shiny");
        translationBuilder.add(PokemonGen1Photos.ONIX_SHINY, "Onix Shiny");
        translationBuilder.add(PokemonGen1Photos.DROWZEE_SHINY, "Drowzee Shiny");
        translationBuilder.add(PokemonGen1Photos.HYPNO_SHINY, "Hypno Shiny");
        translationBuilder.add(PokemonGen1Photos.KRABBY_SHINY, "Krabby Shiny");
        translationBuilder.add(PokemonGen1Photos.KINGLER_SHINY, "Kingler Shiny");
        translationBuilder.add(PokemonGen1Photos.VOLTORB_SHINY, "Voltorb Shiny");
        translationBuilder.add(PokemonGen1Photos.ELECTRODE_SHINY, "Electrode Shiny");
        translationBuilder.add(PokemonGen1Photos.EXEGGCUTE_SHINY, "Exeggcute Shiny");
        translationBuilder.add(PokemonGen1Photos.EXEGGUTOR_SHINY, "Exeggutor Shiny");
        translationBuilder.add(PokemonGen1Photos.CUBONE_SHINY, "Cubone Shiny");
        translationBuilder.add(PokemonGen1Photos.MAROWAK_SHINY, "Marowak Shiny");
        translationBuilder.add(PokemonGen1Photos.HITMONLEE_SHINY, "Hitmonlee Shiny");
        translationBuilder.add(PokemonGen1Photos.HITMONCHAN_SHINY, "Hitmonchan Shiny");
        translationBuilder.add(PokemonGen1Photos.LICKITUNG_SHINY, "Lickitung Shiny");
        translationBuilder.add(PokemonGen1Photos.KOFFING_SHINY, "Koffing Shiny");
        translationBuilder.add(PokemonGen1Photos.WEEZING_SHINY, "Weezing Shiny");
        translationBuilder.add(PokemonGen1Photos.RHYHORN_SHINY, "Rhyhorn Shiny");
        translationBuilder.add(PokemonGen1Photos.RHYDON_SHINY, "Rhydon Shiny");
        translationBuilder.add(PokemonGen1Photos.CHANSEY_SHINY, "Chansey Shiny");
        translationBuilder.add(PokemonGen1Photos.TANGELA_SHINY, "Tangela Shiny");
        translationBuilder.add(PokemonGen1Photos.KANGASKHAN_SHINY, "Kangaskhan Shiny");
        translationBuilder.add(PokemonGen1Photos.HORSEA_SHINY, "Horsea Shiny");
        translationBuilder.add(PokemonGen1Photos.SEADRA_SHINY, "Seadra Shiny");
        translationBuilder.add(PokemonGen1Photos.GOLDEEN_SHINY, "Goldeen Shiny");
        translationBuilder.add(PokemonGen1Photos.SEAKING_SHINY, "Seaking Shiny");
        translationBuilder.add(PokemonGen1Photos.STARYU_SHINY, "Staryu Shiny");
        translationBuilder.add(PokemonGen1Photos.STARMIE_SHINY, "Starmie Shiny");
        translationBuilder.add(PokemonGen1Photos.MR_MIME_SHINY, "Mr.Mime Shiny");
        translationBuilder.add(PokemonGen1Photos.SCYTHER_SHINY, "Scyther Shiny");
        translationBuilder.add(PokemonGen1Photos.JYNX_SHINY, "Jynx Shiny");
        translationBuilder.add(PokemonGen1Photos.ELECTABUZZ_SHINY, "Electabuzz Shiny");
        translationBuilder.add(PokemonGen1Photos.MAGMAR_SHINY, "Magmar Shiny");
        translationBuilder.add(PokemonGen1Photos.PINSIR_SHINY, "Pinsir Shiny");
        translationBuilder.add(PokemonGen1Photos.TAUROS_SHINY, "Tauros Shiny");
        translationBuilder.add(PokemonGen1Photos.MAGIKARP_SHINY, "Magikarp Shiny");
        translationBuilder.add(PokemonGen1Photos.GYARADOS_SHINY, "Gyarados Shiny");
        translationBuilder.add(PokemonGen1Photos.LAPRAS_SHINY, "Lapras Shiny");
        translationBuilder.add(PokemonGen1Photos.DITTO_SHINY, "Ditto Shiny");
        translationBuilder.add(PokemonGen1Photos.EEVEE_SHINY, "Eevee Shiny");
        translationBuilder.add(PokemonGen1Photos.VAPOREON_SHINY, "Vaporeon Shiny");
        translationBuilder.add(PokemonGen1Photos.JOLTEON_SHINY, "Jolteon Shiny");
        translationBuilder.add(PokemonGen1Photos.FLAREON_SHINY, "Flareon Shiny");
        translationBuilder.add(PokemonGen1Photos.PORYGON_SHINY, "Porygon Shiny");
        translationBuilder.add(PokemonGen1Photos.OMANYTE_SHINY, "Omanyte Shiny");
        translationBuilder.add(PokemonGen1Photos.OMASTAR_SHINY, "Omastar Shiny");
        translationBuilder.add(PokemonGen1Photos.KABUTO_SHINY, "Kabuto Shiny");
        translationBuilder.add(PokemonGen1Photos.KABUTOPS_SHINY, "Kabutops Shiny");
        translationBuilder.add(PokemonGen1Photos.AERODACTYL_SHINY, "Aerodactyl Shiny");
        translationBuilder.add(PokemonGen1Photos.SNORLAX_SHINY, "Snorlax Shiny");
        translationBuilder.add(PokemonGen1Photos.ARTICUNO_SHINY, "Articuno Shiny");
        translationBuilder.add(PokemonGen1Photos.ZAPDOS_SHINY, "Zapdos Shiny");
        translationBuilder.add(PokemonGen1Photos.MOLTRES_SHINY, "Moltres Shiny");
        translationBuilder.add(PokemonGen1Photos.DRATINI_SHINY, "Dratini Shiny");
        translationBuilder.add(PokemonGen1Photos.DRAGONAIR_SHINY, "Dragonair Shiny");
        translationBuilder.add(PokemonGen1Photos.DRAGONITE_SHINY, "Dragonite Shiny");
        translationBuilder.add(PokemonGen1Photos.MEWTWO_SHINY, "Mewtwo Shiny");
        translationBuilder.add(PokemonGen1Photos.MEW_SHINY, "Mew Shiny");
    }

    private void genTwo(TranslationBuilder translationBuilder) {
        // gen 2 normal
        translationBuilder.add(PokemonGen2Photos.CHIKORITA, "Chikorita");
        translationBuilder.add(PokemonGen2Photos.BAYLEEF, "Bayleef");
        translationBuilder.add(PokemonGen2Photos.MEGANIUM, "Meganium");
        translationBuilder.add(PokemonGen2Photos.CYNDAQUIL, "Cyndaquil");
        translationBuilder.add(PokemonGen2Photos.QUILAVA, "Quilava");
        translationBuilder.add(PokemonGen2Photos.TYPHLOSION, "Typhlosion");
        translationBuilder.add(PokemonGen2Photos.TOTODILE, "Totodile");
        translationBuilder.add(PokemonGen2Photos.CROCONAW, "Croconaw");
        translationBuilder.add(PokemonGen2Photos.FERALIGATR, "Feraligatr");
        translationBuilder.add(PokemonGen2Photos.SENTRET, "Sentret");
        translationBuilder.add(PokemonGen2Photos.FURRET, "Furret");
        translationBuilder.add(PokemonGen2Photos.HOOTHOOT, "Hoothoot");
        translationBuilder.add(PokemonGen2Photos.NOCTOWL, "Noctowl");
        translationBuilder.add(PokemonGen2Photos.LEDYBA, "Ledyba");
        translationBuilder.add(PokemonGen2Photos.LEDIAN, "Ledian");
        translationBuilder.add(PokemonGen2Photos.SPINARAK, "Spinarak");
        translationBuilder.add(PokemonGen2Photos.ARIADOS, "Ariados");
        translationBuilder.add(PokemonGen2Photos.CROBAT, "Crobat");
        translationBuilder.add(PokemonGen2Photos.CHINCHOU, "Chinchou");
        translationBuilder.add(PokemonGen2Photos.LANTURN, "Lanturn");
        translationBuilder.add(PokemonGen2Photos.PICHU, "Pichu");
        translationBuilder.add(PokemonGen2Photos.CLEFFA, "Cleffa");
        translationBuilder.add(PokemonGen2Photos.IGGLYBUFF, "Igglybuff");
        translationBuilder.add(PokemonGen2Photos.TOGEPI, "Togepi");
        translationBuilder.add(PokemonGen2Photos.TOGETIC, "Togetic");
        translationBuilder.add(PokemonGen2Photos.NATU, "Natu");
        translationBuilder.add(PokemonGen2Photos.XATU, "Xatu");
        translationBuilder.add(PokemonGen2Photos.MAREEP, "Mareep");
        translationBuilder.add(PokemonGen2Photos.FLAAFFY, "Flaaffy");
        translationBuilder.add(PokemonGen2Photos.AMPHAROS, "Ampharos");
        translationBuilder.add(PokemonGen2Photos.BELLOSSOM, "Bellossom");
        translationBuilder.add(PokemonGen2Photos.MARILL, "Marill");
        translationBuilder.add(PokemonGen2Photos.AZUMARILL, "Azumarill");
        translationBuilder.add(PokemonGen2Photos.SUDOWOODO, "Sudowoodo");
        translationBuilder.add(PokemonGen2Photos.POLITOED, "Politoed");
        translationBuilder.add(PokemonGen2Photos.HOPPIP, "Hoppip");
        translationBuilder.add(PokemonGen2Photos.SKIPLOOM, "Skiploom");
        translationBuilder.add(PokemonGen2Photos.JUMPLUFF, "Jumpluff");
        translationBuilder.add(PokemonGen2Photos.AIPOM, "Aipom");
        translationBuilder.add(PokemonGen2Photos.SUNKERN, "Sunkern");
        translationBuilder.add(PokemonGen2Photos.SUNFLORA, "Sunflora");
        translationBuilder.add(PokemonGen2Photos.YANMA, "Yanma");
        translationBuilder.add(PokemonGen2Photos.WOOPER, "Wooper");
        translationBuilder.add(PokemonGen2Photos.QUAGSIRE, "Quagsire");
        translationBuilder.add(PokemonGen2Photos.ESPEON, "Espeon");
        translationBuilder.add(PokemonGen2Photos.UMBREON, "Umbreon");
        translationBuilder.add(PokemonGen2Photos.MURKROW, "Murkrow");
        translationBuilder.add(PokemonGen2Photos.SLOWKING, "Slowking");
        translationBuilder.add(PokemonGen2Photos.MISDREAVUS, "Misdreavus");
        translationBuilder.add(PokemonGen2Photos.UNOWN_A, "Unown A");
        translationBuilder.add(PokemonGen2Photos.UNOWN_B, "Unown B");
        translationBuilder.add(PokemonGen2Photos.UNOWN_C, "Unown C");
        translationBuilder.add(PokemonGen2Photos.UNOWN_D, "Unown D");
        translationBuilder.add(PokemonGen2Photos.UNOWN_E, "Unown E");
        translationBuilder.add(PokemonGen2Photos.UNOWN_EXCLAMATION, "Unown Exclamation");
        translationBuilder.add(PokemonGen2Photos.UNOWN_F, "Unown F");
        translationBuilder.add(PokemonGen2Photos.UNOWN_G, "Unown G");
        translationBuilder.add(PokemonGen2Photos.UNOWN_H, "Unown H");
        translationBuilder.add(PokemonGen2Photos.UNOWN_I, "Unown I");
        translationBuilder.add(PokemonGen2Photos.UNOWN_J, "Unown J");
        translationBuilder.add(PokemonGen2Photos.UNOWN_K, "Unown K");
        translationBuilder.add(PokemonGen2Photos.UNOWN_L, "Unown L");
        translationBuilder.add(PokemonGen2Photos.UNOWN_M, "Unown M");
        translationBuilder.add(PokemonGen2Photos.UNOWN_N, "Unown N");
        translationBuilder.add(PokemonGen2Photos.UNOWN_O, "Unown O");
        translationBuilder.add(PokemonGen2Photos.UNOWN_P, "Unown P");
        translationBuilder.add(PokemonGen2Photos.UNOWN_Q, "Unown Q");
        translationBuilder.add(PokemonGen2Photos.UNOWN_QUESTION, "Unown Question");
        translationBuilder.add(PokemonGen2Photos.UNOWN_R, "Unown R");
        translationBuilder.add(PokemonGen2Photos.UNOWN_S, "Unown S");
        translationBuilder.add(PokemonGen2Photos.UNOWN_T, "Unown T");
        translationBuilder.add(PokemonGen2Photos.UNOWN_U, "Unown U");
        translationBuilder.add(PokemonGen2Photos.UNOWN_V, "Unown V");
        translationBuilder.add(PokemonGen2Photos.UNOWN_W, "Unown W");
        translationBuilder.add(PokemonGen2Photos.UNOWN_X, "Unown X");
        translationBuilder.add(PokemonGen2Photos.UNOWN_Y, "Unown Y");
        translationBuilder.add(PokemonGen2Photos.UNOWN_Z, "Unown Z");
        translationBuilder.add(PokemonGen2Photos.WOBBUFFET, "Wobbuffet");
        translationBuilder.add(PokemonGen2Photos.GIRAFARIG, "Girafarig");
        translationBuilder.add(PokemonGen2Photos.PINECO, "Pineco");
        translationBuilder.add(PokemonGen2Photos.FORRETRESS, "Forretress");
        translationBuilder.add(PokemonGen2Photos.DUNSPARCE, "Dunsparce");
        translationBuilder.add(PokemonGen2Photos.GLIGAR, "Gligar");
        translationBuilder.add(PokemonGen2Photos.STEELIX, "Steelix");
        translationBuilder.add(PokemonGen2Photos.SNUBBULL, "Snubbull");
        translationBuilder.add(PokemonGen2Photos.GRANBULL, "Granbull");
        translationBuilder.add(PokemonGen2Photos.QWILFISH, "Qwilfish");
        translationBuilder.add(PokemonGen2Photos.SCIZOR, "Scizor");
        translationBuilder.add(PokemonGen2Photos.SHUCKLE, "Shuckle");
        translationBuilder.add(PokemonGen2Photos.HERACROSS, "Heracross");
        translationBuilder.add(PokemonGen2Photos.SNEASEL, "Sneasel");
        translationBuilder.add(PokemonGen2Photos.TEDDIURSA, "Teddiursa");
        translationBuilder.add(PokemonGen2Photos.URSARING, "Ursaring");
        translationBuilder.add(PokemonGen2Photos.SLUGMA, "Slugma");
        translationBuilder.add(PokemonGen2Photos.MAGCARGO, "Magcargo");
        translationBuilder.add(PokemonGen2Photos.SWINUB, "Swinub");
        translationBuilder.add(PokemonGen2Photos.PILOSWINE, "Piloswine");
        translationBuilder.add(PokemonGen2Photos.CORSOLA, "Corsola");
        translationBuilder.add(PokemonGen2Photos.REMORAID, "Remoraid");
        translationBuilder.add(PokemonGen2Photos.OCTILLERY, "Octillery");
        translationBuilder.add(PokemonGen2Photos.DELIBIRD, "Delibird");
        translationBuilder.add(PokemonGen2Photos.MANTINE, "Mantine");
        translationBuilder.add(PokemonGen2Photos.SKARMORY, "Skarmory");
        translationBuilder.add(PokemonGen2Photos.HOUNDOUR, "Houndour");
        translationBuilder.add(PokemonGen2Photos.HOUNDOOM, "Houndoom");
        translationBuilder.add(PokemonGen2Photos.KINGDRA, "Kingdra");
        translationBuilder.add(PokemonGen2Photos.PHANPY, "Phanpy");
        translationBuilder.add(PokemonGen2Photos.DONPHAN, "Donphan");
        translationBuilder.add(PokemonGen2Photos.PORYGON2, "Porygon2");
        translationBuilder.add(PokemonGen2Photos.STANTLER, "Stantler");
        translationBuilder.add(PokemonGen2Photos.SMEARGLE, "Smeargle");
        translationBuilder.add(PokemonGen2Photos.TYROGUE, "Tyrogue");
        translationBuilder.add(PokemonGen2Photos.HITMONTOP, "Hitmontop");
        translationBuilder.add(PokemonGen2Photos.SMOOCHUM, "Smoochum");
        translationBuilder.add(PokemonGen2Photos.ELEKID, "Elekid");
        translationBuilder.add(PokemonGen2Photos.MAGBY, "Magby");
        translationBuilder.add(PokemonGen2Photos.MILTANK, "Miltank");
        translationBuilder.add(PokemonGen2Photos.BLISSEY, "Blissey");
        translationBuilder.add(PokemonGen2Photos.RAIKOU, "Raikou");
        translationBuilder.add(PokemonGen2Photos.ENTEI, "Entei");
        translationBuilder.add(PokemonGen2Photos.SUICUNE, "Suicune");
        translationBuilder.add(PokemonGen2Photos.LARVITAR, "Larvitar");
        translationBuilder.add(PokemonGen2Photos.PUPITAR, "Pupitar");
        translationBuilder.add(PokemonGen2Photos.TYRANITAR, "Tyranitar");
        translationBuilder.add(PokemonGen2Photos.LUGIA, "Lugia");
        translationBuilder.add(PokemonGen2Photos.HO_OH, "Ho-Oh");
        translationBuilder.add(PokemonGen2Photos.CELEBI, "Celebi");
        // gen 2 shiny
        translationBuilder.add(PokemonGen2Photos.CHIKORITA_SHINY, "Chikorita Shiny");
        translationBuilder.add(PokemonGen2Photos.BAYLEEF_SHINY, "Bayleef Shiny");
        translationBuilder.add(PokemonGen2Photos.MEGANIUM_SHINY, "Meganium Shiny");
        translationBuilder.add(PokemonGen2Photos.CYNDAQUIL_SHINY, "Cyndaquil Shiny");
        translationBuilder.add(PokemonGen2Photos.QUILAVA_SHINY, "Quilava Shiny");
        translationBuilder.add(PokemonGen2Photos.TYPHLOSION_SHINY, "Typhlosion Shiny");
        translationBuilder.add(PokemonGen2Photos.TOTODILE_SHINY, "Totodile Shiny");
        translationBuilder.add(PokemonGen2Photos.CROCONAW_SHINY, "Croconaw Shiny");
        translationBuilder.add(PokemonGen2Photos.FERALIGATR_SHINY, "Feraligatr Shiny");
        translationBuilder.add(PokemonGen2Photos.SENTRET_SHINY, "Sentret Shiny");
        translationBuilder.add(PokemonGen2Photos.FURRET_SHINY, "Furret Shiny");
        translationBuilder.add(PokemonGen2Photos.HOOTHOOT_SHINY, "Hoothoot Shiny");
        translationBuilder.add(PokemonGen2Photos.NOCTOWL_SHINY, "Noctowl Shiny");
        translationBuilder.add(PokemonGen2Photos.LEDYBA_SHINY, "Ledyba Shiny");
        translationBuilder.add(PokemonGen2Photos.LEDIAN_SHINY, "Ledian Shiny");
        translationBuilder.add(PokemonGen2Photos.SPINARAK_SHINY, "Spinarak Shiny");
        translationBuilder.add(PokemonGen2Photos.ARIADOS_SHINY, "Ariados Shiny");
        translationBuilder.add(PokemonGen2Photos.CROBAT_SHINY, "Crobat Shiny");
        translationBuilder.add(PokemonGen2Photos.CHINCHOU_SHINY, "Chinchou Shiny");
        translationBuilder.add(PokemonGen2Photos.LANTURN_SHINY, "Lanturn Shiny");
        translationBuilder.add(PokemonGen2Photos.PICHU_SHINY, "Pichu Shiny");
        translationBuilder.add(PokemonGen2Photos.CLEFFA_SHINY, "Cleffa Shiny");
        translationBuilder.add(PokemonGen2Photos.IGGLYBUFF_SHINY, "Igglybuff Shiny");
        translationBuilder.add(PokemonGen2Photos.TOGEPI_SHINY, "Togepi Shiny");
        translationBuilder.add(PokemonGen2Photos.TOGETIC_SHINY, "Togetic Shiny");
        translationBuilder.add(PokemonGen2Photos.NATU_SHINY, "Natu Shiny");
        translationBuilder.add(PokemonGen2Photos.XATU_SHINY, "Xatu Shiny");
        translationBuilder.add(PokemonGen2Photos.MAREEP_SHINY, "Mareep Shiny");
        translationBuilder.add(PokemonGen2Photos.FLAAFFY_SHINY, "Flaaffy Shiny");
        translationBuilder.add(PokemonGen2Photos.AMPHAROS_SHINY, "Ampharos Shiny");
        translationBuilder.add(PokemonGen2Photos.BELLOSSOM_SHINY, "Bellossom Shiny");
        translationBuilder.add(PokemonGen2Photos.MARILL_SHINY, "Marill Shiny");
        translationBuilder.add(PokemonGen2Photos.AZUMARILL_SHINY, "Azumarill Shiny");
        translationBuilder.add(PokemonGen2Photos.SUDOWOODO_SHINY, "Sudowoodo Shiny");
        translationBuilder.add(PokemonGen2Photos.POLITOED_SHINY, "Politoed Shiny");
        translationBuilder.add(PokemonGen2Photos.HOPPIP_SHINY, "Hoppip Shiny");
        translationBuilder.add(PokemonGen2Photos.SKIPLOOM_SHINY, "Skiploom Shiny");
        translationBuilder.add(PokemonGen2Photos.JUMPLUFF_SHINY, "Jumpluff Shiny");
        translationBuilder.add(PokemonGen2Photos.AIPOM_SHINY, "Aipom Shiny");
        translationBuilder.add(PokemonGen2Photos.SUNKERN_SHINY, "Sunkern Shiny");
        translationBuilder.add(PokemonGen2Photos.SUNFLORA_SHINY, "Sunflora Shiny");
        translationBuilder.add(PokemonGen2Photos.YANMA_SHINY, "Yanma Shiny");
        translationBuilder.add(PokemonGen2Photos.WOOPER_SHINY, "Wooper Shiny");
        translationBuilder.add(PokemonGen2Photos.QUAGSIRE_SHINY, "Quagsire Shiny");
        translationBuilder.add(PokemonGen2Photos.ESPEON_SHINY, "Espeon Shiny");
        translationBuilder.add(PokemonGen2Photos.UMBREON_SHINY, "Umbreon Shiny");
        translationBuilder.add(PokemonGen2Photos.MURKROW_SHINY, "Murkrow Shiny");
        translationBuilder.add(PokemonGen2Photos.SLOWKING_SHINY, "Slowking Shiny");
        translationBuilder.add(PokemonGen2Photos.MISDREAVUS_SHINY, "Misdreavus Shiny");
        translationBuilder.add(PokemonGen2Photos.UNOWN_A_SHINY, "Unown A Shiny");
        translationBuilder.add(PokemonGen2Photos.UNOWN_B_SHINY, "Unown B Shiny");
        translationBuilder.add(PokemonGen2Photos.UNOWN_C_SHINY, "Unown C Shiny");
        translationBuilder.add(PokemonGen2Photos.UNOWN_D_SHINY, "Unown D Shiny");
        translationBuilder.add(PokemonGen2Photos.UNOWN_E_SHINY, "Unown E Shiny");
        translationBuilder.add(PokemonGen2Photos.UNOWN_EXCLAMATION_SHINY, "Unown Exclamation Shiny");
        translationBuilder.add(PokemonGen2Photos.UNOWN_F_SHINY, "Unown F Shiny");
        translationBuilder.add(PokemonGen2Photos.UNOWN_G_SHINY, "Unown G Shiny");
        translationBuilder.add(PokemonGen2Photos.UNOWN_H_SHINY, "Unown H Shiny");
        translationBuilder.add(PokemonGen2Photos.UNOWN_I_SHINY, "Unown I Shiny");
        translationBuilder.add(PokemonGen2Photos.UNOWN_J_SHINY, "Unown J Shiny");
        translationBuilder.add(PokemonGen2Photos.UNOWN_K_SHINY, "Unown K Shiny");
        translationBuilder.add(PokemonGen2Photos.UNOWN_L_SHINY, "Unown L Shiny");
        translationBuilder.add(PokemonGen2Photos.UNOWN_M_SHINY, "Unown M Shiny");
        translationBuilder.add(PokemonGen2Photos.UNOWN_N_SHINY, "Unown N Shiny");
        translationBuilder.add(PokemonGen2Photos.UNOWN_O_SHINY, "Unown O Shiny");
        translationBuilder.add(PokemonGen2Photos.UNOWN_P_SHINY, "Unown P Shiny");
        translationBuilder.add(PokemonGen2Photos.UNOWN_Q_SHINY, "Unown Q Shiny");
        translationBuilder.add(PokemonGen2Photos.UNOWN_QUESTION_SHINY, "Unown Question Shiny");
        translationBuilder.add(PokemonGen2Photos.UNOWN_R_SHINY, "Unown R Shiny");
        translationBuilder.add(PokemonGen2Photos.UNOWN_S_SHINY, "Unown S Shiny");
        translationBuilder.add(PokemonGen2Photos.UNOWN_T_SHINY, "Unown T Shiny");
        translationBuilder.add(PokemonGen2Photos.UNOWN_U_SHINY, "Unown U Shiny");
        translationBuilder.add(PokemonGen2Photos.UNOWN_V_SHINY, "Unown V Shiny");
        translationBuilder.add(PokemonGen2Photos.UNOWN_W_SHINY, "Unown W Shiny");
        translationBuilder.add(PokemonGen2Photos.UNOWN_X_SHINY, "Unown X Shiny");
        translationBuilder.add(PokemonGen2Photos.UNOWN_Y_SHINY, "Unown Y Shiny");
        translationBuilder.add(PokemonGen2Photos.UNOWN_Z_SHINY, "Unown Z Shiny");
        translationBuilder.add(PokemonGen2Photos.WOBBUFFET_SHINY, "Wobbuffet Shiny");
        translationBuilder.add(PokemonGen2Photos.GIRAFARIG_SHINY, "Girafarig Shiny");
        translationBuilder.add(PokemonGen2Photos.PINECO_SHINY, "Pineco Shiny");
        translationBuilder.add(PokemonGen2Photos.FORRETRESS_SHINY, "Forretress Shiny");
        translationBuilder.add(PokemonGen2Photos.DUNSPARCE_SHINY, "Dunsparce Shiny");
        translationBuilder.add(PokemonGen2Photos.GLIGAR_SHINY, "Gligar Shiny");
        translationBuilder.add(PokemonGen2Photos.STEELIX_SHINY, "Steelix Shiny");
        translationBuilder.add(PokemonGen2Photos.SNUBBULL_SHINY, "Snubbull Shiny");
        translationBuilder.add(PokemonGen2Photos.GRANBULL_SHINY, "Granbull Shiny");
        translationBuilder.add(PokemonGen2Photos.QWILFISH_SHINY, "Qwilfish Shiny");
        translationBuilder.add(PokemonGen2Photos.SCIZOR_SHINY, "Scizor Shiny");
        translationBuilder.add(PokemonGen2Photos.SHUCKLE_SHINY, "Shuckle Shiny");
        translationBuilder.add(PokemonGen2Photos.HERACROSS_SHINY, "Heracross Shiny");
        translationBuilder.add(PokemonGen2Photos.SNEASEL_SHINY, "Sneasel Shiny");
        translationBuilder.add(PokemonGen2Photos.TEDDIURSA_SHINY, "Teddiursa Shiny");
        translationBuilder.add(PokemonGen2Photos.URSARING_SHINY, "Ursaring Shiny");
        translationBuilder.add(PokemonGen2Photos.SLUGMA_SHINY, "Slugma Shiny");
        translationBuilder.add(PokemonGen2Photos.MAGCARGO_SHINY, "Magcargo Shiny");
        translationBuilder.add(PokemonGen2Photos.SWINUB_SHINY, "Swinub Shiny");
        translationBuilder.add(PokemonGen2Photos.PILOSWINE_SHINY, "Piloswine Shiny");
        translationBuilder.add(PokemonGen2Photos.CORSOLA_SHINY, "Corsola Shiny");
        translationBuilder.add(PokemonGen2Photos.REMORAID_SHINY, "Remoraid Shiny");
        translationBuilder.add(PokemonGen2Photos.OCTILLERY_SHINY, "Octillery Shiny");
        translationBuilder.add(PokemonGen2Photos.DELIBIRD_SHINY, "Delibird Shiny");
        translationBuilder.add(PokemonGen2Photos.MANTINE_SHINY, "Mantine Shiny");
        translationBuilder.add(PokemonGen2Photos.SKARMORY_SHINY, "Skarmory Shiny");
        translationBuilder.add(PokemonGen2Photos.HOUNDOUR_SHINY, "Houndour Shiny");
        translationBuilder.add(PokemonGen2Photos.HOUNDOOM_SHINY, "Houndoom Shiny");
        translationBuilder.add(PokemonGen2Photos.KINGDRA_SHINY, "Kingdra Shiny");
        translationBuilder.add(PokemonGen2Photos.PHANPY_SHINY, "Phanpy Shiny");
        translationBuilder.add(PokemonGen2Photos.DONPHAN_SHINY, "Donphan Shiny");
        translationBuilder.add(PokemonGen2Photos.PORYGON2_SHINY, "Porygon2 Shiny");
        translationBuilder.add(PokemonGen2Photos.STANTLER_SHINY, "Stantler Shiny");
        translationBuilder.add(PokemonGen2Photos.SMEARGLE_SHINY, "Smeargle Shiny");
        translationBuilder.add(PokemonGen2Photos.TYROGUE_SHINY, "Tyrogue Shiny");
        translationBuilder.add(PokemonGen2Photos.HITMONTOP_SHINY, "Hitmontop Shiny");
        translationBuilder.add(PokemonGen2Photos.SMOOCHUM_SHINY, "Smoochum Shiny");
        translationBuilder.add(PokemonGen2Photos.ELEKID_SHINY, "Elekid Shiny");
        translationBuilder.add(PokemonGen2Photos.MAGBY_SHINY, "Magby Shiny");
        translationBuilder.add(PokemonGen2Photos.MILTANK_SHINY, "Miltank Shiny");
        translationBuilder.add(PokemonGen2Photos.BLISSEY_SHINY, "Blissey Shiny");
        translationBuilder.add(PokemonGen2Photos.RAIKOU_SHINY, "Raikou Shiny");
        translationBuilder.add(PokemonGen2Photos.ENTEI_SHINY, "Entei Shiny");
        translationBuilder.add(PokemonGen2Photos.SUICUNE_SHINY, "Suicune Shiny");
        translationBuilder.add(PokemonGen2Photos.LARVITAR_SHINY, "Larvitar Shiny");
        translationBuilder.add(PokemonGen2Photos.PUPITAR_SHINY, "Pupitar Shiny");
        translationBuilder.add(PokemonGen2Photos.TYRANITAR_SHINY, "Tyranitar Shiny");
        translationBuilder.add(PokemonGen2Photos.LUGIA_SHINY, "Lugia Shiny");
        translationBuilder.add(PokemonGen2Photos.HO_OH_SHINY, "Ho-Oh Shiny");
        translationBuilder.add(PokemonGen2Photos.CELEBI_SHINY, "Celebi Shiny");

    }
}
